method : 'bayes'
name : 'hsi_densenet'
metric :
  goal : 'minimize'
  name : 'val_loss'

parameters :
  lr :
    min : 0.0000005
    max : 0.00001
  # weight_decay :
  #   min : 0.0000005
  #   max : 0.00001
  BATCH_SIZE:
    value : 64
    # distribution: 'q_log_uniform_values'
    # max: 128
    # min: 32
    # q: 8
  epochs :
    value : 150

  model_size :
    # value : [6,12,48,32]
    values :
      - [12, 18, 24, 6]
      - [12, 18, 10, 5]
      - [6,12,24,16]
      - [6,12,24,32]
      # - [6,12,48,32]
  # lr :
  #   value :  0.00000944
  weight_decay :
    value : 0.000002
  dir :
    value: 'models/hsi/dense_net'
  num_classes :
    value: 98
  fold:
    value : 4

  in_channels :
    value : 152
  model_name :
    value : 'hsi_densenet'
  H :
    value : 40
  W :
    value : 24
  C :
    value : 152

  # optimizer :
  #   values : ["adam", "sgd"]

