BATCH_SIZE: 128
C: 168
H: 40
MAX_EPOCHS: 300
W: 24
apply_BAM: false
apply_bam: false
ckpt_file_name: '{epoch}-{val_loss:.2f}-{val_accuracy:.2f}'
compression_factor: 0.3
data_dir: Data/hsi
data_type: original
densenet_variant: densenet_mini
dir: results/hsi
fold: 4
k: 32
lr: 7.44e-06
modality: hsi
model_name: densenet
num_classes: 96
num_workers: 8
preprocessing: none
weight_decay: 3.0e-08
