BATCH_SIZE: 128
C: 147
H: 40
W: 24
ckpt_file_name: '{epoch}-{val_loss:.2f}-{val_accuracy:.2f}'
dir: models/hsi/dense_net
fold: 4
in_channels: 147
lr: 7.44e-06
model_name: hsi_densenet
num_classes: 96
preprocessing: msc
weight_decay: 3.0e-08
