method : 'bayes'
name : 'hsi_densenet_sweep'
metric :
  goal : 'minimize'
  name : 'total_val_loss'

parameters :
  num_workers:
    value : 8
  preprocessing:
    value : none
  modality:
    value : hsi
  data_type:
    value : maskedFull
  dir :
    value: 'results/hsi/sweep/densenet'
  data_dir :
    value : 'Data/hsi_masked'
  num_classes :
    value: 96

  model_name :
    value : 'sparse_bam_densenet'
  H :
    value : 40
  W :
    value : 24
  C :
    value : 168
  lr :
    # value : 4.0e-05
    min : 1.0e-5
    max : 4.0e-05
  weight_decay :
    value : 3.8e-07
    # min : 1.0e-7
    # max : 1.0e-5
  BATCH_SIZE:
    value : 64
    # distribution: 'q_log_uniform_values'
    # max: 128
    # min: 32
    # q: 8
  MAX_EPOCHS :
    value : 200
  accumulate_grad_batches:
    value : 2
  model_size :
    value : [18,24,16,10]
    # values :
    #   - [12, 18, 24, 6]
    #   - [12, 18, 10, 5]
    #   - [6,12,24,16]
    #   - [6,12,24,32]
    #   - [6,12,48,32]
  compression_factor :
    value : 0.25
    # values :
      # - 0.2
      # - 0.25
      # - 0.27

  k :
    value : 24
    # values :
    #   - 16
    #   - 24
    #   - 32
    #   - 48
      # - 64
  activation_func :
    value : 'prelu'
    # values :
    #   - 'prelu'
    #   -  'elu'
    #   - 'silu'
    #   - 'gelu'
  densenet_variant :
    value :
        - 24
        - 18
        - 16
        - 10
    # values : ["densenet_mini", "densenet"]

  # optimizer :
  #   values : ["adam", "sgd"]

  head_model_ckpt :
    value : ''
  r :
    # values :
    #   - 1
    #   - 2
      # - 3
    value : 2
  temperature :
    distribution : 'normal'
    mu : 0.7
    sigma : 0.05

  sparsity_threshold :
    distribution : 'normal'
    mu : 0.0
    sigma : 0.1

  head_model_name :
    value: 'densenet'
  beta :
    distribution : 'uniform'
    min : 1.0e-07
    max : 1.0e-04

  scheduler_name :
    value: exponential_decay_lr_scheduler    # cosine_warm_restarts_decay_lr_scheduler , exponential_decay_lr_scheduler , 'cosine_annealing_lr_scheduler'

  exponential_decay_lr_scheduler_params:
    value:
      gamma : 0.99

  # cosine_warm_restarts_decay_lr_scheduler_params:
  #   value :
  #     T_0:  5
  #     T_mult: 2
  #     eta_min:  0.0000002
  #     decay: 0.8
