method : 'bayes'
name : 'hsi_densenet'
metric :
  goal : 'minimize'
  name : 'cross_entropy_val_loss'

parameters :
  num_workers:
    value : 8
  preprocessing:
    value : none
  modality:
    value : hsi
  data_type:
    value : maskedBAM
  dir :
    value: 'results/hsi/sweep/densenet'
  data_dir :
    value : 'Data/hsi_masked'
  num_classes :
    value: 96
  fold:
    value : 4

  model_name :
    value : 'densenet'
  H :
    value : 40
  W :
    value : 24
  C :
    value : 168
  lr :
    value :  0.0000125
    # min : 0.000005
    # max : 0.00001
  weight_decay :
    value : 0.000000038
    # min : 1.0e-7
    # max : 1.0e-5
  BATCH_SIZE:
    value : 64
    # distribution: 'q_log_uniform_values'
    # max: 128
    # min: 32
    # q: 8
  MAX_EPOCHS :
    value : 500
  accumulate_grad_batches:
    value : 3
  model_size :
    value : [12,18,24, 6]
    # values :
    #   - [12, 18, 24, 6]
    #   - [12, 18, 10, 5]
    #   - [6,12,24,16]
    #   - [6,12,24,32]
    #   - [6,12,48,32]
  compression_factor :
    value : 0.3
    # values :
      # - 0.2
      # - 0.25
      # - 0.27

  k :
    value : 48
    # values :
    #   - 16
    #   - 24
    #   - 32
    #   - 48
      # - 64
  activation_func :
    value : 'prelu'
    # values :
    #   - 'prelu'
    #   -  'elu'
    #   - 'silu'
    #   - 'gelu'
  densenet_variant :
    value :
        - 12
        - 18
        - 24
        - 6
    # values : ["densenet_mini", "densenet"]

  # optimizer :
  #   values : ["adam", "sgd"]

  head_model_ckpt :
    value : results/hsi/classes-96/densenet-12-18-24-6__maskedTrimmed__none--epoch=149-val_loss=0.00-val_accuracy=0.86.ckpt
  r :
    values :
      - 1
      - 2
      # - 3
  temperature :
    distribution : 'uniform'
    min : 0.45
    max : 0.55

  sparsity_threshold :
    distribution : 'normal'
    mu : 0.06
    sigma : 0.1

  head_model_name :
    value: 'densenet'
  beta :
    distribution : 'uniform'
    min : 0.0000007
    max : 0.000002
    # value : !!float 1e-4
    # values :
    #   - !!float 1e-4
    #   - !!float 1e-5
    #   - !!float 1e-6
  # scheduler_config
  scheduler_name :
    value: cosine_warm_restarts_decay_lr_scheduler    # cosine_warm_restarts_decay_lr_scheduler , exponential_decay_lr_scheduler , 'cosine_annealing_lr_scheduler'

  cosine_warm_restarts_decay_lr_scheduler_params:
    value :
      T_0:  5
      T_mult: 2
      eta_min:  0.0000002
      decay: 0.8
