dir : 'models/ensemble/logs'

num_classes : 96

BATCH_SIZE : 64
lr : 0.000021

in_channels : 168
weight_decay : 0.000001
ckpt_file_name : 'deep_ensemble--{epoch}-{val_loss:.2f}-{val_accuracy:.2f}'
model_name : 'wheat_deep_ensemble'


deep_ensemble :
  num_classes : 96
  model_name : 'deep_ensemble'
  base_models_ct: 4
  activation_func : 'prelu'
  fold : 4
  dir : 'results/ensemble/deep_ensemble'
  ckpt_file_name : 'deep_ensemble--{epoch}-{val_loss:.2f}-{val_accuracy:.2f}'
  BATCH_SIZE : 64
  weight_decay : 0.000001
  accumulate_grad_batches : 2
  MAX_EPOCHS : 60
  dropout_rate : 0.16
  lr : 0.000011

  scheduler_name : cosine_warm_restarts_decay_lr_scheduler    # cosine_warm_restarts_decay_lr_scheduler , exponential_decay_lr_scheduler , 'cosine_annealing_lr_scheduler'

  cosine_warm_restarts_decay_lr_scheduler_params:
    T_0: 10
    T_mult: 2
    eta_min: 0.0000002
    decay: 0.75

  exponential_decay_lr_scheduler_params:
    gamma: 0.95

  cosine_annealing_lr_scheduler_params:
    T_max: 160
    eta_min: 0.0000001

