BATCH_SIZE: 64
C: 168
EarlyStopping:
  min_delta: 0.0001
  mode: min
  monitor: total_val_loss
  patience: 30
  verbose: true
H: 40
MAX_EPOCHS: 200
ModelCheckpoint:
  mode: min
  monitor: total_val_loss
  save_top_k: 1
  verbose: true
W: 24
accumulate_grad_batches: 2
ckpt_file_name: '{epoch}-{val_loss:.2f}-{val_accuracy:.2f}'
cosine_annealing_lr_scheduler_params:
  T_max: 250
  eta_min: 1.0e-07
cosine_warm_restarts_decay_lr_scheduler_params:
  T_0: 10
  T_mult: 2
  decay: 0.7
  eta_min: 1.0e-06
data_dir: Data/hsi/

dir: results/hsi
exponential_decay_lr_scheduler_params:
  gamma: 0.985

lr: 3.5e-05
modality: hsi
model_name: densenet
num_classes: 96
num_workers: 8
preprocessing: none
scheduler_name: exponential_decay_lr_scheduler
weight_decay: 3.8e-07

model_config:
  n_attention_modules: 3
  n_classes: 96
  input_dimension: 168
  uses_attention: True

data_config:
  preprocessing: ${preprocessing}
  data_dir: ${data_dir}
  BATCH_SIZE: ${BATCH_SIZE}
  num_workers: ${num_workers}
  input_dimension: ${C}
  num_classes: ${num_classes}
